version: "3"

networks:
  monitoring:

volumes:
  prom_data:
  grafana_data:

services:
  loki:
    image: grafana/loki:2.3.0
    container_name: loki
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - "3100:3100"
    networks:
      - monitoring
    restart: always

  promtail:
    image: grafana/promtail:2.3.0
    container_name: promtail
    command: -config.file=/etc/promtail/config.yml
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers
      - /operations/monitoring/prometheus/config/promtail.yml:/etc/promtail/config.yml
    networks:
      - monitoring
    restart: always

  prometheus:
    image: bitnami/prometheus:2.29.1
    container_name: prometheus
    command:
      - "--config.file=${PROM_CONFIGDIR}/prometheus.yml"
      - "--storage.tsdb.path=${PROM_DATADIR}"
      - '--storage.tsdb.retention.time=30d'
    ports:
      - 9090:9090
    volumes:
      - "/operations/monitoring/prometheus/config:${PROM_CONFIGDIR}"
      - "prom_data:${PROM_DATADIR}"
    networks:
      - monitoring
    restart: always

  grafana:
    image: grafana/grafana:8.1.2
    container_name: grafana
    environment:
      GF_INSTALL_PLUGINS: "grafana-clock-panel,grafana-simple-json-datasource"
    ports:
      - "3000:3000"
    volumes:
      # - "/operations/monitoring/grafana/config:${GRAFANA_CONFIGDIR}"
      - "grafana_data:${GRAFANA_DATADIR}"
    networks:
      - monitoring
    restart: always

  node-exporter:
    image: quay.io/prometheus/node-exporter:v1.2.2
    container_name: node-exporter
    command: --path.rootfs=/host
    ports:
      - "9100:9100"
    volumes:
      - "/:/host:ro,rslave"
    networks:
      - monitoring
    restart: always
