---
dependencies:
  - role: 0x0i.systemd
    tags: ['never']

galaxy_info:
  author: Ahmad Wilson
  role_name: kafka
  description: Kafka, a distributed and fault tolerant stream-processing platform
  company: "O1.IO"
  license: license (MIT)
  min_ansible_version: 2.6
  platforms:
    - name: EL
      versions:
        - all
    - name: Debian
      versions:
        - all
    - name: Fedora
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
  galaxy_tags:
    - kafka
    - stream
    - processing
