---
dependencies:
  - role: o1labs.cloud.openssh
    tags: ['never']

galaxy_info:
  author: O1 Labs
  role_name: base
  description: Applies basic setup of system services supporting cloud-native infrastructure
  company: "O1.IO"
  license: MIT
  min_ansible_version: 2.5
  platforms:
    - name: Debian
      versions:
        - jessie
        - stretch
    - name: Ubuntu
      versions:
        - xenial
        - bionic
        - cosmic
  galaxy_tags:
    - cloud
    - infrastructure
    - containerization
    - security
