---
- name: Ensure existence of runtime dir
  become: true
  file:
    path: "{{ ops_runtime_dir }}"
    state: directory
    mode: 0777

- name: Generate Geth compose config
  become: true
  template:
    src: "docker-compose.yml.j2"
    dest: "{{ ops_runtime_dir }}/docker-compose.yml"
    owner: "root"
    group: "root"
    mode: 0644
    backup: true
  register: "geth_compose"

- name: Generate Geth compose environment vars
  become: true
  template:
    src: ".env.j2"
    dest: "{{ config_env_file }}"
    owner: "root"
    group: "root"
    mode: 0644
    backup: true
  vars:
    conf: "{{ _default_config|combine(config) }}"
    env_conf: "{{ env_vars }}"
  register: "compose_env"

- name: Run docker-compose up
  community.docker.docker_compose:
    project_src: "{{ ops_runtime_dir }}"
    state: "{{ target_state }}"
    services: "{{ target_services }}"
