global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]
  - job_name: "geth"
    metrics_path: "/debug/metrics/prometheus"
    static_configs:
      - targets: ["geth:6060"]
  - job_name: "geth-exporter"
    static_configs:
      - targets: ["geth-exporter:9090"]
  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]
