---
driver:
  name: docker

# Special config for enabling systemd init
default_driver_config: &default_driver_config
  run_command: /sbin/init
  cap_add:
    - SYS_ADMIN
  run_options:
    env: container=docker
  volume:
    - /sys/fs/cgroup:/sys/fs/cgroup
  provision_command:
    - sed -i 's/UsePAM yes/UsePAM no/g' /etc/ssh/sshd_config
    - systemctl enable sshd.service

transport:
  # TODO: remove with better solution than workaround:
  # https://github.com/test-kitchen/test-kitchen/issues/1035
  max_ssh_sessions: 6

provisioner:
  hosts: test-kitchen
  name: ansible_playbook
  require_pip: true
  ansible_version: 2.9.4
  ansible_verbose: true
  ansible_cfg_path: test/ansible.cfg
  idempotency_test: true
  require_chef_for_busser: false
  require_ruby_for_busser: false

verifier:
  name: inspec

platforms:
  - name: centos-7
    driver_config:
      <<: *default_driver_config
    provisioner:
      ansible_cfg_path: test/ansible-legacy.cfg
  - name: fedora-30
    driver_config:
      <<: *default_driver_config
      provision_command:
        - sed -i 's/UsePAM yes/UsePAM no/g' /etc/ssh/sshd_config
        - systemctl enable sshd.service
        - yum -y install python-pip
  - name: fedora-31
    driver_config:
      <<: *default_driver_config
      provision_command:
        - sed -i 's/UsePAM yes/UsePAM no/g' /etc/ssh/sshd_config
        - systemctl enable sshd.service
        - yum -y install python-pip
  - name: ubuntu-16.04
    driver_config:
      <<: *default_driver_config
      provision_command:
        - sed -i 's/UsePAM yes/UsePAM no/g' /etc/ssh/sshd_config
        - systemctl enable ssh.service
  - name: ubuntu-18.04
    driver_config:
      <<: *default_driver_config
      provision_command:
        - sed -i 's/UsePAM yes/UsePAM no/g' /etc/ssh/sshd_config
        - systemctl enable ssh.service
  - name: ubuntu-19.04
    driver_config:
      <<: *default_driver_config
      provision_command:
        - sed -i 's/UsePAM yes/UsePAM no/g' /etc/ssh/sshd_config
        - systemctl enable ssh.service
  - name: debian-8
    driver_config:
      <<: *default_driver_config
      run_command: /lib/systemd/systemd
      provision_command:
        - sed -i 's/UsePAM yes/UsePAM no/g' /etc/ssh/sshd_config
        - systemctl enable ssh.service
    provisioner:
      ansible_cfg_path: test/ansible-legacy.cfg
  - name: debian-9
    driver_config:
      <<: *default_driver_config
      run_command: /lib/systemd/systemd
      provision_command:
        - sed -i 's/UsePAM yes/UsePAM no/g' /etc/ssh/sshd_config
        - systemctl enable ssh.service

suites:
  - name: config_authorized_keys
    provisioner:
      playbook: test/integration/config/authorized_keys/default_playbook.yml
    verifier:
      inspec_tests:
        - path: test/integration/config/authorized_keys
  - name: config_client
    provisioner:
      playbook: test/integration/config/config_client/default_playbook.yml
    verifier:
      inspec_tests:
        - path: test/integration/config/config_client
  - name: config_known_hosts
    provisioner:
      playbook: test/integration/config/known_hosts/default_playbook.yml
    verifier:
      inspec_tests:
        - path: test/integration/config/known_hosts
  - name: config_service
    provisioner:
      playbook: test/integration/config/config_service/default_playbook.yml
    verifier:
      inspec_tests:
        - path: test/integration/config/config_service
  - name: config_user_identities
    provisioner:
      playbook: test/integration/config/user_identities/default_playbook.yml
    verifier:
      inspec_tests:
        - path: test/integration/config/user_identities
  - name: setup_ssh_agent
    provisioner:
      playbook: test/integration/setup/ssh_agent/default_playbook.yml
    verifier:
      inspec_tests:
        - path: test/integration/setup/ssh_agent
  - name: uninstall
    provisioner:
      playbook: test/integration/uninstall/default_playbook.yml
      idempotency_test: false
    verifier:
      inspec_tests:
        - path: test/integration/uninstall
