---
galaxy_info:
  author: Ahmad Wilson
  role_name: Ansible
  description: Ansible - a software provisioning, configuration management and application deployment tool
  company: "O1.IO"
  license: license (MIT)
  min_ansible_version: 2.5
  platforms:
    - name: EL
      versions:
        - all
    - name: Debian
      versions:
        - all
    - name: Fedora
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
  galaxy_tags:
    - ansible
    - configuration
    - provisioning
    - deployment
    - management
