---
- name: Create bridged monitoring network for components to communicate
  community.docker.docker_network:
    name: monitoring

- name: Deploy monitoring services
  include_tasks: "compose/setup.yml"
  when: target_services is defined and target_services|length > 0
  tags:
    - monitoring

- name: Add [monitored] services to monitoring network
  docker_network:
    name: monitoring
    connected: "{{ monitored_services }}"
    appends: yes
