---
- name: Create bridged Operator network for components to communicate
  community.docker.docker_network:
    name: operator

- name: Start operator service
  community.docker.docker_container:
    name: operator
    image: "{{ image }}"
    published_ports:
      - "{{ api_port }}:1001"
    networks:
      - name: operator

- name: Enable HTTPS server communication
  when: enable_https
  include_tasks: "https_setup.yml"
