---
- name: Uninstall provisioned container components
  when: uninstall|bool == true
  block:
    - name: Broadcast uninstall signal
      command: /bin/true
      notify: Container uninstall
  always:
    - name: End play following uninstallation
      meta: end_play

- name: Create bridged Operator network for components to communicate
  community.docker.docker_network:
    name: operator

- name: Start operator service
  community.docker.docker_container:
    name: operator
    image: "{{ image }}"
    command: ["flask", "run", "--host={{ api_host }}", "--port=1001"]
    published_ports:
      - "{{ api_port }}:1001"
    networks:
      - name: operator
    cpus: "{{ cpus }}"
    memory: "{{ memory }}"
    restart_policy: "{{ restart_policy }}"

- name: Enable HTTPS server communication
  when: enable_https|bool
  include_tasks: "https_setup.yml"
