---
- name: Ensure existence of runtime dir
  become: true
  file:
    path: "{{ ops_runtime_dir }}"
    state: directory
    mode: 0755

- name: Setup Operator infrastructure topology
  include_tasks: "{{ setup_mode }}/setup.yml"
  tags:
    - setup
