---
- name: Download Kibana archive ({{ archive_url }})
  become: true
  when: install_type == "archive"
  get_url:
    url: "{{ archive_url }}"
    dest: "/tmp/{{ archive_url | urlsplit('path') | basename }}"
    checksum: "{{ (archive_checksum|length > 0) | ternary(checksum_format+':'+archive_checksum, '') }}"
    owner: "{{ kibana_user }}"
    group: "{{ kibana_user }}"
    mode: '0775'
  register: archive_tmp
  tags:
    - install
    - archive

- name: Extract Kibana archive
  become: true
  when: install_type == "archive"
  unarchive:
    src: "{{ archive_tmp.dest }}"
    dest: "{{ install_dir }}"
    creates: "{{ install_dir }}/bin"
    owner: "{{ kibana_user }}"
    group: "{{ kibana_user }}"
    mode: '0775'
    extra_opts:
      - --strip-components
      - '1'
    remote_src: true
  tags:
    - install
    - archive
