---
dependencies:
  - 0x0i.systemd

galaxy_info:
  author: Ahmad Wilson
  role_name: grafana
  description: Grafana - an analytics and monitoring observability platform
  company: "O1.IO"
  license: license (MIT)
  min_ansible_version: 2.5
  platforms:
    - name: EL
      versions:
        - all
    - name: Debian
      versions:
        - all
    - name: Fedora
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
  galaxy_tags:
    - grafana
    - dashboards
    - monitoring
    - alerting
    - prometheus
