---
- name: Provision instance monitoring services
  hosts: monitored
  roles:
    - role: "../../roles/monitoring"
      vars:
        target_services: [ 'node-exporter' ]

- name: Setup Prometheus observability service
  hosts: prometheus
  roles:
    - role: "../../roles/monitoring"
      vars:
        target_services: [ 'prometheus' ]
        monitored_services: [ 'chainlink', 'postgres' ]
        prometheus_scrape_configs:
          - job_name: "prometheus"
            static_configs:
              - targets: ["prometheus:9090"]
          - job_name: "chainlink"
            metrics_path: "/metrics"
            static_configs:
              - targets: ["chainlink:6688" ]
          - job_name: "node-exporter"
            static_configs:
              - targets: ["node-exporter:9100"]
          
- name: Setup Grafana observability service
  hosts: grafana
  roles:
    - role: "../../roles/monitoring"
      vars:
        target_services: [ 'grafana' ]
