---
- name: Ensure existence of runtime dirs
  become: true
  file:
    path: "{{ dir }}"
    state: directory
    mode: 0777
  loop:
    - /tmp/monitoring/compose
    - /tmp/monitoring/config
  loop_control:
    loop_var: dir

- copy:
    src: "{{ role_path }}/files/monitoring/{{ file }}"
    dest: "/tmp/monitoring/{{ file }}"
  loop:
    - "config/prometheus.yml"
    - "config/promtail.yml"
    - "compose/docker-compose.yml"
    - "compose/.env"
  loop_control:
    loop_var: file

- name: Deploy monitoring services compose
  community.docker.docker_compose:
    project_src: /tmp/monitoring/compose
    state: "{{ target_state }}"
    services: "{{ monitoring_services }}"
    env_file: "{{ _monitoring_env_file }}"
