---
galaxy_info:
  author: Ahmad Wilson
  role_name: vim
  description: vim (Vi-IMproved), a powerful flexible text editor for Linux operating systems
  company: O1.IO
  license: license (MIT)
  min_ansible_version: 2.5
  platforms:
    - name: EL
      versions:
        - all
    - name: Debian
      versions:
        - all
    - name: Fedora
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
  galaxy_tags:
    - vim
    - text
    - editor
    - vi
