---
driver:
  name: docker

# Special config for enabling systemd init
default_driver_config: &default_driver_config
  run_command: /sbin/init
  cap_add:
    - SYS_ADMIN
  run_options:
    env: container=docker
  volume:
    - /sys/fs/cgroup:/sys/fs/cgroup
  provision_command:
    - sed -i 's/UsePAM yes/UsePAM no/g' /etc/ssh/sshd_config
    - systemctl enable sshd.service

transport:
  # TODO: remove with better solution than workaround:
  # https://github.com/test-kitchen/test-kitchen/issues/1035
  max_ssh_sessions: 6

provisioner:
  hosts: test-kitchen
  name: ansible_playbook
  require_pip: true
  ansible_version: 2.9.4
  ansible_verbose: true
  ansible_cfg_path: test/ansible.cfg
  requirements_path: test/requirements-test.yml
  idempotency_test: true
  require_chef_for_busser: false
  require_ruby_for_busser: false

verifier:
  name: inspec

platforms:
  - name: centos-7
    driver_config:
      <<: *default_driver_config
    provisioner:
      ansible_cfg_path: test/ansible-legacy.cfg
  - name: ubuntu-16.04
    driver_config:
      <<: *default_driver_config
      provision_command:
        - sed -i 's/UsePAM yes/UsePAM no/g' /etc/ssh/sshd_config
        - systemctl enable ssh.service
  - name: ubuntu-18.04
    driver_config:
      <<: *default_driver_config
      provision_command:
        - sed -i 's/UsePAM yes/UsePAM no/g' /etc/ssh/sshd_config
        - systemctl enable ssh.service
  - name: debian-8
    driver_config:
      <<: *default_driver_config
      run_command: /lib/systemd/systemd
      provision_command:
        - sed -i 's/UsePAM yes/UsePAM no/g' /etc/ssh/sshd_config
        - systemctl enable ssh.service
    provisioner:
      ansible_cfg_path: test/ansible-legacy.cfg
  - name: debian-9
    driver_config:
      <<: *default_driver_config
      run_command: /lib/systemd/systemd
      provision_command:
        - sed -i 's/UsePAM yes/UsePAM no/g' /etc/ssh/sshd_config
        - systemctl enable ssh.service

suites:
  - name: install_gem
    provisioner:
      playbook: test/integration/install/install_gem/default_playbook.yml
    verifier:
      inspec_tests:
        - path: test/integration/install/install_gem
  - name: install_package
    provisioner:
      playbook: test/integration/install/install_package/default_playbook.yml
    verifier:
      inspec_tests:
        - path: test/integration/install/install_package
  - name: install_plugins_by_fluentd
    provisioner:
      playbook: test/integration/install/plugins_by_fluentd/default_playbook.yml
    verifier:
      inspec_tests:
        - path: test/integration/install/plugins_by_fluentd
  - name: config_fluentconf
    provisioner:
      playbook: test/integration/config/fluent_conf/default_playbook.yml
    verifier:
      inspec_tests:
        - path: test/integration/config/fluent_conf
  - name: launch_tdagent
    provisioner:
      playbook: test/integration/launch/td_agent/default_playbook.yml
    verifier:
      inspec_tests:
        - path: test/integration/launch/td_agent
  - name: launch_fluentd
    provisioner:
      playbook: test/integration/launch/fluentd/default_playbook.yml
    verifier:
      inspec_tests:
        - path: test/integration/launch/fluentd
  - name: install_plugins_by_tdagent
    provisioner:
      playbook: test/integration/install/plugins_by_tdagent/default_playbook.yml
    verifier:
      inspec_tests:
        - path: test/integration/install/plugins_by_tdagent
  - name: uninstall
    provisioner:
      playbook: test/integration/uninstall/default_playbook.yml
      idempotency_test: false
    verifier:
      inspec_tests:
        - path: test/integration/uninstall
