---
- name: Create Alertmanager installation directory
  become: true
  file:
    path: "{{ alertmgr_installdir }}"
    state: directory
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_user }}"
  when: '"alertmanager" in managed_services'
  tags:
    - install
    - alertmanager

- name: Download Alertmanager archive ({{ alertmgr_archive_url }})
  become: true
  when: '"alertmanager" in managed_services'
  get_url:
    url: "{{ alertmgr_archive_url }}"
    dest: "/tmp/{{ alertmgr_archive_url | urlsplit('path') | basename }}"
    checksum: "{{ (alertmgr_archive_checksum|length > 0) | ternary(alertmgr_checksum_format+':'+alertmgr_archive_checksum, '') }}"
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_user }}"
    mode: '0775'
  register: alertmgr_archive_tmp
  tags:
    - install
    - archive
    - alertmanager

- name: Extract Alertmanager archive
  become: true
  when: '"alertmanager" in managed_services'
  unarchive:
    src: "{{ alertmgr_archive_tmp.dest }}"
    dest: "{{ alertmgr_installdir }}"
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_user }}"
    mode: '0775'
    remote_src: true
    extra_opts:
      - --strip-components
      - '1'
    creates: "{{ alertmgr_installdir }}/alertmanager"
  tags:
    - install
    - archive
    - alertmanager
