---
- name: Create Prometheus exporter installation directory
  become: true
  file:
    path: "{{ exporter.path|default(exporter_installdir) }}/{{ exporter.name }}"
    state: directory
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_user }}"
  tags:
    - install
    - exporters

- name: Extract Prometheus exporter archive
  become: true
  unarchive:
    src: "{{ exporter.url }}"
    dest: "{{ exporter.path|default(exporter_installdir) }}/{{ exporter.name }}"
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_user }}"
    mode: '0775'
    remote_src: true
    extra_opts:
      - --strip-components
      - '1'
  tags:
    - install
    - archive
    - exporters
