---
# kitchen configuration for CI testing
driver:
  name: docker

# Special config for enabling systemd init
default_driver_config: &default_driver_config
  run_command: /sbin/init
  cap_add:
    - SYS_ADMIN
  run_options:
    env: container=docker
  volume:
    - /sys/fs/cgroup:/sys/fs/cgroup
  provision_command:
    - sed -i 's/UsePAM yes/UsePAM no/g' /etc/ssh/sshd_config
    - systemctl enable sshd.service
    - yum install -y net-tools

transport:
  # TODO: remove with better solution than workaround:
  # https://github.com/test-kitchen/test-kitchen/issues/1035
  max_ssh_sessions: 6

provisioner:
  hosts: test-kitchen
  name: ansible_playbook
  require_chef_for_busser: false
  require_ruby_for_busser: false
  ansible_verbosity: 2
  ansible_verbose: true
  requirements_path: test/requirements-test.yml

verifier:
  name: inspec

platforms:
  - name: centos-7
    driver_config:
      <<: *default_driver_config
  - name: fedora-32
    driver_config:
      <<: *default_driver_config
      provision_command:
        - sed -i 's/UsePAM yes/UsePAM no/g' /etc/ssh/sshd_config
        - systemctl enable sshd.service
        - yum -y install python-pip net-tools
    provisioner:
      require_pip: true
      ansible_cfg_path: test/ansible.cfg
  - name: fedora-33
    driver_config:
      <<: *default_driver_config
      provision_command:
        - sed -i 's/UsePAM yes/UsePAM no/g' /etc/ssh/sshd_config
        - systemctl enable sshd.service
        - yum -y install python-pip net-tools
    provisioner:
      require_pip: true
      ansible_cfg_path: test/ansible.cfg
  - name: ubuntu-16.04
    driver_config:
      <<: *default_driver_config
      provision_command:
        - sed -i 's/UsePAM yes/UsePAM no/g' /etc/ssh/sshd_config
        - systemctl enable ssh.service
        - apt install -y net-tools
  - name: ubuntu-18.04
    driver_config:
      <<: *default_driver_config
      provision_command:
        - sed -i 's/UsePAM yes/UsePAM no/g' /etc/ssh/sshd_config
        - systemctl enable ssh.service
        - apt install -y net-tools
  - name: ubuntu-20.04
    driver_config:
      <<: *default_driver_config
      provision_command:
        - sed -i 's/UsePAM yes/UsePAM no/g' /etc/ssh/sshd_config
        - systemctl enable ssh.service
        - apt install -y net-tools
  - name: debian-9
    driver_config:
      <<: *default_driver_config
      run_command: /lib/systemd/systemd
      provision_command:
        - sed -i 's/UsePAM yes/UsePAM no/g' /etc/ssh/sshd_config
        - systemctl enable ssh.service
        - apt install -y net-tools

suites:
  - name: install_archive
    provisioner:
      playbook: test/integration/install/install_archive/default_playbook.yml
      ansible_extra_flags: '--skip-tags=config,launch'
    verifier:
      inspec_tests:
        - path: test/integration/install/install_archive
  - name: server_properties
    provisioner:
      playbook: test/integration/config/server_properties/default_playbook.yml
      ansible_extra_flags: '--skip-tags=launch'
    verifier:
      inspec_tests:
        - path: test/integration/config/server_properties
  - name: jvm_options
    provisioner:
      playbook: test/integration/config/jvm_options/default_playbook.yml
      ansible_extra_flags: '--skip-tags=launch'
    verifier:
      inspec_tests:
        - path: test/integration/config/jvm_options
  - name: log4j_properties
    provisioner:
      playbook: test/integration/config/log4j_properties/default_playbook.yml
      ansible_extra_flags: '--skip-tags=launch'
    verifier:
      inspec_tests:
        - path: test/integration/config/log4j_properties
  - name: launch_service
    provisioner:
      playbook: test/integration/launch/launch_service/default_playbook.yml
    verifier:
      inspec_tests:
        - path: test/integration/launch/launch_service
  - name: uninstall
    provisioner:
      playbook: test/integration/uninstall/default_playbook.yml
    verifier:
      inspec_tests:
        - path: test/integration/uninstall
