---
- name: Ensure existence of runtime dir
  become: true
  file:
    path: "{{ ops_runtime_dir }}"
    state: directory
    mode: 0777

- name: Generate Teku compose config
  become: true
  template:
    src: "docker-compose.yml.j2"
    dest: "{{ ops_runtime_dir }}/docker-compose.yml"
    owner: "root"
    group: "root"
    mode: 0644
    backup: true
  register: "teku_compose"

- name: Generate Teku beacon compose environment vars
  become: true
  template:
    src: ".env.j2"
    dest: "{{ beacon_env_file }}"
    owner: "root"
    group: "root"
    mode: 0644
    backup: true
  vars:
    conf: "{{ _default_beacon_config|combine(beacon_config) }}"
    env_conf: "{{ beacon_env_vars }}"
  register: "beacon_compose_env"

- name: Generate Teku validator compose config
  become: true
  template:
    src: ".env.j2"
    dest: "{{ validator_env_file }}"
    owner: "root"
    group: "root"
    mode: 0644
    backup: true
  vars:
    conf: "{{ _default_validator_config|combine(validator_config) }}"
    env_conf: "{{ validator_env_vars }}"
  register: "validator_compose_env"

- name: Run docker-compose up
  community.docker.docker_compose:
    project_src: "{{ ops_runtime_dir }}"
    state: "{{ target_state }}"
    services: "{{ target_services }}"
