---
dependencies:
  - role: 0x0i.systemd
    tags: ['never']

galaxy_info:
  author: Ahmad Wilson
  role_name: kibana
  description: Kibana, an analytics and visualization platform designed to operate with Elasticsearch
  company: "O1.IO"
  license: license (MIT)
  min_ansible_version: 2.5
  platforms:
    - name: EL
      versions:
        - all
    - name: Debian
      versions:
        - all
    - name: Fedora
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
  galaxy_tags:
    - kibana
    - analytics
    - visualization
    - elasticsearch
