---
setup_mode: container
target_state: present
ops_runtime_dir: /var/tmp/operator

image: 0labs/operator:latest
api_host: operator
api_port: 1001
http_port: 80
https_port: 443

enable_https: false
cert_dir: /var/www/certbot
email:
domain_names: []
