---
galaxy_info:
  author: Ahmad Wilson
  role_name: journald
  description: Journald, a system service that collects and stores logging data
  company: "O1.IO"
  license: license (MIT)
  min_ansible_version: 2.5
  platforms:
    - name: EL
      versions:
        - all
    - name: Debian
      versions:
        - all
    - name: Fedora
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
  galaxy_tags:
    - journald
    - logging
    - systemd
    - events
