---
setup_mode: compose
target_state: present
target_services: [ 'geth', 'geth-exporter']
_ops_runtime_dir: /tmp/geth
_config_env_file: "{{ _ops_runtime_dir }}/.env"

geth_image: 0labs/geth:latest
geth_net: rinkeby
geth_config_dir: /etc/geth
host_data_dir: /operations/ethereum/geth/data
geth_data_dir: /root/.ethereum

geth_p2p_port: 30303
geth_rpc_port: 8545
geth_metrics_port: 6060
geth_metrics_addr: 0.0.0.0
geth_external_addr: 127.0.0.1

exporter_image: hunterlong/gethexporter:latest
exporter_rpc_addr: http://geth:8545
exporter_port: 10090

monitoring_services: [ 'node-exporter' ]
_monitoring_env_file: .env
restart_policy: always

_default_config:
  Eth:
    SyncMode: light
  Node:
    DataDir: "{{ geth_data_dir }}"
    HTTPHost: 0.0.0.0
    HTTPCors: "['*']"
    HTTPVirtualHosts: "['*']"
  Metrics:
    Enabled: "true"
    HTTP: 0.0.0.0
config: {}
