---
setup_mode: compose
target_state: present
target_services: [ 'geth', 'geth-exporter']
_ops_runtime_dir: /var/tmp/geth
_config_env_file: "{{ _ops_runtime_dir }}/.env"

image: 0labs/geth:latest
chain: rinkeby
config_dir: /etc/geth
host_data_dir: /operations/ethereum/geth/data
data_dir: /root/.ethereum

p2p_port: 30303
rpc_port: 8545
metrics_port: 6060
metrics_addr: 0.0.0.0
external_addr: 127.0.0.1

exporter_image: hunterlong/gethexporter:latest
exporter_rpc_addr: http://geth:8545
exporter_port: 10090

restart_policy: unless-stopped

_default_config:
  Eth:
    SyncMode: light
  Node:
    DataDir: "{{ geth_data_dir }}"
    HTTPHost: 0.0.0.0
    HTTPCors: "['*']"
    HTTPVirtualHosts: "['*']"
  Metrics:
    Enabled: "true"
    HTTP: 0.0.0.0
config: {}
